server:
  port: 8082
  servlet:
    context-path: /prod   #意义何在？
#角色信息配置,自定义
role:
  name: admin
  descriptiption: 管理员
  permissionIds: 20,21,22
#连接数据库
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/users?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
     username: root
     password: 123456
  